language: node_js
before_script:
- npm install -g typescript
- tsc
- npm pack
deploy:
  skip_cleanup: true
  provider: npm
  email: t.voslar@gmail.com
  api_key:
    secure: SQbegNeyXVL766QKqzwhyeHmmzNHvRP2i4/LLpkvwj4HqO4a7P6k/VXSzSosYWbTulCyd3FUUUfR7arl6VM9bMuNXC++6J4qjuV4QV5/SnT3nrjswyWn3pfv9Q3v1ErS6MxK+h6KQfYtQ7yLfIaUzz2gsXkOGwd8PKytxL7m7mjtbYuIfyYewFZRJZfO0luXWslZJc7GX9d328wrAG6feP/haNN0k04oj/cVuFfOBcQyJJyDgkU9QgmE6R58KNWo4ptURu64rToW20k2fEWLS8lBedlbK9A21IkbyP82c9CXbUATaTJ1sivv0qmjcxHzzMNUfAEW15/OjJB1DrUNLN73h0/CUIdhatVwRv6cO/HDWGxvwvSsi5lUstWGwfGXIc0UgFl6qTKTN3Nmz6v1lyAw9ySvipLpYDzTfXes65dvXoLWwGsYDoo3aRetyTZCAiM4519JKm8+qQQBic4h39s1oKOjWj1FAlkc9dQCq7OPBDmHbjoU5/Brz+C/pOUhvDFlmMMkc3e4tB34C7Y1eGvWk1gtoIont4SlyrloRROUmKzKYxU2QhujZ1yhl0sVdiKgO+tu3BSUHyaFCgG9KMNmOwPcidR946jm6TWx6F1mZUYCjkGCf5g1TiQltxCEOgrYNLVLPllwgEGaKxy5XuzQ/7kL+pYaggX9ydihvoQ=
  on:
    tags: true
    repo: blabu-com/logger
